services:

  db:
    image: postgres:16
    container_name: sistemavisitantes-db
    restart: always

    env_file:
      - .env.db

    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistemavisitantes -d sistemavisitantes"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sistemavisitantes-web
    restart: always

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  db_data:
  media_data:
  static_data: