# Generated by Django 6.0.5 on 2026-05-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('nit', 'NIT'), ('ce', 'C.E.')], max_length=50)),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('visitor_type', models.CharField(choices=[('externo', 'Externo'), ('proveedor', 'Proveedor'), ('contratista', 'Contratista')], max_length=50)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('visita', 'Visita'), ('reunion', 'Reunión'), ('entrega', 'Entrega')], max_length=100)),
                ('person_to_visit', models.CharField(max_length=100)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('area', models.CharField(max_length=100)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitas_fotos/')),
                ('token_qr', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('ingresado', 'Ingresado'), ('salido', 'Salido')], default='ingresado', max_length=20)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
    ]
