# Generated by Django 6.0.5 on 2026-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('ingresado', 'En Instalaciones'), ('salido', 'Salida Registrada')], default='ingresado', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document_type',
            field=models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('entrevistado', 'Entrevistado'), ('proveedor', 'Proveedor'), ('visitante', 'Visitante Externo'), ('contratista', 'Contratista')], max_length=50),
        ),
    ]
