# Generated by Django 6.0.5 on 2026-05-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visit_exit_time_alter_visit_reason_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('medica', 'Médica'), ('laboral', 'Laboral'), ('calamidad', 'Calamidad Doméstica'), ('personal', 'Personal'), ('visita', 'Visita General'), ('entrega', 'Entrega / Proveedor'), ('entrevista', 'Entrevista'), ('contratista', 'Contratista')], max_length=100, null=True),
        ),
    ]
