# Generated by Django 6.0.5 on 2026-05-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_visit_reason_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área de Destino'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora de Entrada'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='person_to_visit',
            field=models.CharField(max_length=100, verbose_name='Persona a Visitar'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitas_fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle Adicional'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('visita_general', 'Visita General'), ('entrega_proveedor', 'Entrega / Proveedor'), ('entrevista', 'Entrevista de Trabajo'), ('contratista', 'Trabajo de Contratista'), ('reunion', 'Reunión de Negocios'), ('otro', 'Otro')], max_length=100, null=True, verbose_name='Motivo de Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('ingresado', 'En Instalaciones'), ('salido', 'Salida Registrada')], default='ingresado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='token_qr',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True, verbose_name='Token QR'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='document_type',
            field=models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte')], max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('entrevistado', 'Entrevistado'), ('proveedor', 'Proveedor'), ('visitante', 'Visitante Externo'), ('contratista', 'Contratista')], max_length=50, verbose_name='Tipo de Visitante'),
        ),
    ]
