# Generated by Django 6.0.5 on 2026-05-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_visit_options_alter_visitor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document_id', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('area', models.CharField(max_length=100, verbose_name='Área/Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Empleado Activo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AlterField(
            model_name='visit',
            name='reason_type',
            field=models.CharField(blank=True, choices=[('visita_general', 'Visita General'), ('entrega_proveedor', 'Entrega / Proveedor'), ('entrevista', 'Entrevista de Trabajo'), ('contratista', 'Trabajo de Contratista'), ('reunion', 'Reunión de Negocios'), ('otro', 'Otro')], max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('entrevistado', 'Entrevistado'), ('proveedor', 'Proveedor'), ('visitante', 'Visitante Externo'), ('contratista', 'Contratista')], max_length=50, verbose_name='Tipo ingreso/salida'),
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Salida')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Retorno')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de Salida')),
                ('status', models.CharField(choices=[('ACTIVO', 'En Permiso'), ('FINALIZADO', 'Retornó')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Movimiento de Empleado',
                'verbose_name_plural': 'Movimientos de Empleados',
            },
        ),
    ]
