# Generated by Django 5.2.14 on 2026-06-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_visit_correo_notificar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(max_length=100, verbose_name='Tipo de Permiso')),
                ('status', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('token_qr', models.CharField(blank=True, max_length=8, unique=True, verbose_name='Token QR')),
                ('correo_notificar', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo a Notificar')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Permiso de Empleado',
                'verbose_name_plural': 'Permisos de Empleados',
            },
        ),
    ]
