# Generated by Django 5.2.14 on 2026-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0007_employeepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('entrevistado', 'Entrevistado'), ('proveedor', 'Proveedor'), ('visitante_externo', 'Visitante Externo'), ('contratista', 'Contratista')], max_length=50, verbose_name='Tipo ingreso/salida'),
        ),
    ]
