# Generated by Django 5.2.14 on 2026-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_employee_alter_visit_reason_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='correo_notificar',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo a Notificar'),
        ),
    ]
