# Generated by Django 5.2.14 on 2026-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_alter_visitor_visitor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Emergencia'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Celular'),
        ),
    ]
