# Generated by Django 5.2.14 on 2026-08-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_visitor_emergency_contact_visitor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número Contacto de Emergencia'),
        ),
    ]
