# Generated by Django 5.2.14 on 2026-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_visitor_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco Contacto de Emergencia'),
        ),
    ]
