# Generated by Django 5.2.14 on 2026-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0011_visitor_emergency_contact_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='emergency_contact',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Emergencia'),
        ),
    ]
