# Generated by Django 5.2.14 on 2026-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_remove_visitor_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='document_type',
            field=models.CharField(choices=[('cedula', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('pasaporte', 'Pasaporte')], default='cedula', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Celular'),
        ),
    ]
