# Generated by Django 5.2.14 on 2026-07-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('document_type', models.CharField(choices=[('cedula', 'CC'), ('ce', 'CE'), ('pasaporte', 'PAS')], default='cedula', max_length=20, verbose_name='Tipo de Documento')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Trabajo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('LABORAL', 'Laboral'), ('CALAMIDAD', 'Calamidad Doméstica'), ('MEDICINA', 'Medicina'), ('PERSONAL', 'Personal')], max_length=20, verbose_name='Tipo de Permiso')),
                ('departure_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Salida')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Regreso')),
                ('detalle_adicional', models.TextField(blank=True, null=True, verbose_name='Detalle / Justificación')),
                ('correo_notificar', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo a Notificar')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='empleados_permisos/', verbose_name='Foto')),
                ('token_qr', models.CharField(blank=True, editable=False, max_length=8, null=True, verbose_name='Token QR')),
                ('status', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Permiso de Empleado',
                'verbose_name_plural': 'Permisos de Empleados',
            },
        ),
    ]
