# Generated by Django 6.0.5 on 2026-05-15 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Cédula/ID')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(choices=[('LABORAL', 'Laboral'), ('CALAMIDAD', 'Calamidad Doméstica'), ('MEDICINA', 'Medicina'), ('PERSONAL', 'Personal')], max_length=20, verbose_name='Tipo de Permiso')),
                ('departure_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Salida')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Regreso')),
                ('status', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Permiso de Empleado',
                'verbose_name_plural': 'Permisos de Empleados',
            },
        ),
    ]
