# Generated by Django 5.2.14 on 2026-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa'),
        ),
    ]
