# Generated by Django 6.0.5 on 2026-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Trabajo'),
        ),
    ]
