# Generated by Django 5.2.14 on 2026-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
    ]
