# Generated by Django 6.0.5 on 2026-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='token_qr',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True, verbose_name='Token QR'),
        ),
    ]
