# Generated by Django 5.2.14 on 2026-08-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco Contacto de Emergencia'),
        ),
    ]
