# Generated by Django 6.0.5 on 2026-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeepermission_token_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='detalle_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle / Justificación'),
        ),
    ]
