# Generated by Django 5.2.14 on 2026-08-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_emergency_contact_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cedula', 'CC'), ('ce', 'CE'), ('pasaporte', 'PAS')], max_length=20, verbose_name='Tipo de Documento')),
                ('document_id', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('area', models.CharField(max_length=100, verbose_name='Área de Trabajo')),
                ('company', models.CharField(default='BOCCHERINI S.A.S', max_length=150, verbose_name='Empresa')),
                ('departure_date', models.DateField(verbose_name='Fecha de Salida')),
                ('departure_time', models.TimeField(verbose_name='Hora de Salida')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detalle / Justificación')),
                ('correo_notificar', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo a Notificar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Empleado')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Salida Temprana',
                'verbose_name_plural': 'Salidas Tempranas',
                'ordering': ['-departure_date', '-departure_time'],
            },
        ),
    ]
