# Generated by Django 5.2.14 on 2026-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeepermission_detalle_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='correo_notificar',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo a Notificar'),
        ),
    ]
