# Generated by Django 5.2.14 on 2026-08-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_earlydeparture'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlydeparture',
            name='autorizado_por',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Autorizado por'),
        ),
    ]
