# Generated by Django 5.2.14 on 2026-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeepermission_correo_notificar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='empleados_permisos/', verbose_name='Foto'),
        ),
    ]
