# Generated by Django 5.2.14 on 2026-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='empleados_permisos/', verbose_name='Foto'),
        ),
    ]
