# Generated by Django 5.2.14 on 2026-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_earlydeparture_autorizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlydeparture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='early_departures/', verbose_name='Fotografía'),
        ),
    ]
